Added blog on contributor workflow
the-guild-org/the-guild-website pull request #346
Opened 2021-04-20 13:36 UTC by tvvignesh

This PR adds the blog on contributor workflow as suggested by @Urigo

2021-04-20 16:06 UTC, Urigo requested changes
Great post!

I've added some small notes.

I think the most important thing for me to emphasize is that what we really care about and trying to solve is making it easier for people who never contributed to open source to start participating, opening that world to them.

The initial step, the first time is the hardest.

We want to show them the path, what's possible and how to get there.

If you can add a bit more about these types of things it would be awesome!

2021-04-20 16:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +Then we started thinking about the next important thing which we can address to make both maintainer's and contributor's lives easier - LABELS
Maybe talk about labels before issue templates?
It's a bigger change

2021-04-20 16:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +Then we started thinking about the next important thing which we can address to make both maintainer's and contributor's lives easier - LABELS
with header that's called something like "Process based Github Labels" or something?

2021-04-20 16:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +
"The goal here was to make it more obvious for anyone who arrives to an issue where exactly it stands and most importantly, what can you do to help advance the solution"

2021-04-20 16:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +Now, [Urigo](https://twitter.com/UriGoldshtein) had an interesting thought process - since we had already published the contributor workflow guide, why not we label issues keeping the same in mind? A
link to the workflow

2021-04-20 16:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +which is how almost workflows look like for every project (Guild or even otherwise) - This is again the initial iteration and we will have more room for improvement over time and you may see more/les
most/almost?

2021-04-20 16:44 UTC, kamilkisiela commented
Preview: https://the-guild-webs-git-fork-tvvignesh-blog-contrib-workflow-15224a.vercel.app/blog/oss-contributor-workflow

2021-04-21 07:12 UTC, tvvignesh commented on pages/blog/oss-contributor-workflow.mdx
> +But as anything goes, it is not without its own set of challenges which advocates us to think of interesting solutions. This stands true in our case as well.
Not sure why we are talking about the "career" aspect here - is it really relevant?

2021-04-21 07:21 UTC, tvvignesh commented on pages/blog/oss-contributor-workflow.mdx
> +which is how almost workflows look like for every project (Guild or even otherwise) - This is again the initial iteration and we will have more room for improvement over time and you may see more/les
Thanks for catching that. It should be either `almost all` or `most`

2021-04-21 07:23 UTC, tvvignesh commented
@Urigo Addressed all your feedback except [this](https://github.com/the-guild-org/the-guild-website/pull/346#discussion_r616817413) which I was not sure of.

2021-04-21 09:06 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +But as anything goes, it is not without its own set of challenges which advocates us to think of interesting solutions. This stands true in our case as well.
yes maybe not that. I guess my point is around that there are benefits for people to contribute to open source and if its hard it's a shame.... I'm sure you can write something much better than I did :)

2021-04-21 09:24 UTC, Urigo approved these changes
as usual, you take my wording and make it 10x better :)

Added small notes but at this point it is ready.

We'll publish it tomorrow

2021-04-21 09:24 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +Making open source more approachable has beneficial for the maintainers, users and the contributors themselves - opening new paths for them that seemed harder before.
is beneficial?  has benefits?
It's worth trying opening new paths?
something like that?

2021-04-21 09:24 UTC, Urigo commented on pages/blog/oss-contributor-workflow.mdx
> +
"We see that improving that is [The Guild's core mission!](https://the-guild.dev/about-us)"

2021-04-22 13:44 UTC, merged