add similar articles in bottom of each blog post
the-guild-org/the-guild-website pull request #624
Opened 2022-02-26 17:07 UTC by B2o5T

related https://github.com/the-guild-org/the-guild-website/issues/603

2022-03-13 20:24 UTC, B2o5T commented on patches/@theguild+components+1.10.0.patch
> ++  }, react.css(_templateObject3$6 || (_templateObject3$6 = _taggedTemplateLiteral(["\n          z-index: 300; // TODO: Used for Docusaurus, remove when no longer needed.\n        "]))), !isModalOpen
saw some bug on mobile with `top: -100vh`, `top: -100%` fix it, need to fix on guild/components also

2022-03-13 20:25 UTC, B2o5T commented on tsconfig.json
> +    "target": "ESNext",
allow use top-level await

2022-03-14 10:32 UTC, n1ru4l requested changes
![image](https://user-images.githubusercontent.com/14338007/158154817-d620e5f8-fa9f-4536-91ae-28d63bac090f.png)

I guess we should avoid referencing the same article? (https://the-guild-website-i7zg9djyk-theguild.vercel.app/blog/graphql-error-handling-with-fp)

2022-03-14 11:32 UTC, n1ru4l approved these changes

2022-03-14 11:33 UTC, n1ru4l commented
@B2o5T Feel free to merge when you feel ready!

2022-03-14 11:48 UTC, B2o5T commented
@n1ru4l it's ready :) just wanted to receive some other approves

2022-03-14 12:34 UTC, charlypoly approved these changes
🚀 🚀 🚀

2022-03-14 12:37 UTC, merged