Cloudflare Slack bot
the-guild-org/the-guild-website pull request #792
Opened 2022-07-26 14:16 UTC by TuvalSimha

Closes #782

2022-07-31 08:18 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +```tmol
```suggestion
```toml
```

2022-07-31 08:18 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +After you finish the installation, Cloudflare creates also `tmol` file, this file contains the name, main, compatibility_date and triggers. To use the triggers, Cloudflare supports Crons and is look
```suggestion
After you finish the installation, Cloudflare creates also `toml` file, this file contains the name, main, compatibility_date and triggers. To use the triggers, Cloudflare supports Crons and is look like that:
```
toml I guess?

2022-07-31 08:18 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +      - 'typescript-operations'
```suggestion
      - typescript
      - typescript-operations
```

2022-07-31 08:19 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +You can find more information and tutorials on how to integrate **Cloudflare Workers** with **GrpahQL Yoga - [LINK](https://www.graphql-yoga.com/docs/integrations/integration-with-cloudflare-workers)
```suggestion
You can find more information and tutorials on how to integrate **Cloudflare Workers** with **GrpahQL Yoga - [link](https://www.graphql-yoga.com/docs/integrations/integration-with-cloudflare-workers)**
```

2022-07-31 08:19 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +... WRITE ANY CODE YOU WANT HERE
```suggestion
  // We use Octokit to use GitHub API
  ... WRITE ANY CODE YOU WANT HERE
```

2022-07-31 08:20 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +- And a lot more examples… ([You can find a lot of examples in Cloudflare docs](https://developers.Cloudflare.com/workers/examples/)).
```suggestion
- Build an entire Slack bot
- Return small HTML page
- JSON return
- Fetch HTML / JSON
- A/B Testing
- Auth with headers
- Schedule processing
- And a lot more examples… ([You can find a lot of examples in Cloudflare docs](https://developers.Cloudflare.com/workers/examples/))
```

2022-07-31 08:21 UTC, B2o5T commented on pages/blog/slack-bot_with_cloudflare.mdx
> +So, let's talk about what we created - **GitHub Slack bot reminder in Cloudflare Workers.**
```suggestion
So, let's talk about what we created - **GitHub Slack bot reminder in Cloudflare Workers**.
```

2022-08-01 06:56 UTC, kamilkisiela commented on pages/blog/slack-bot_with_cloudflare.mdx
> +**GraphQL Yoga,** one of the greatest tools in The Guild, provides a GraphQL server. Our focus is on easy setup, performance and great developer experience. So you can easily integrate it into any pl
```suggestion
**GraphQL Yoga**, one of the greatest tools in The Guild, provides a GraphQL server. Our focus is on easy setup, performance and great developer experience. So you can easily integrate it into any platform besides Node.js.
```

2022-08-01 07:00 UTC, kamilkisiela commented on pages/blog/slack-bot_with_cloudflare.mdx
> +  tags: ['graphql', 'yoga', 'codegen'],
```suggestion
  tags: ['graphql', 'codegen'],
```
The Slack bot doesn't use Yoga. I'm also thinking about a new category for such things, maybe `edge` or `tutorials`? It kind of touches GraphQL and Codegen but the main topic here is CF Worker and its scheduler feature.

2022-08-01 07:03 UTC, kamilkisiela commented on pages/blog/slack-bot_with_cloudflare.mdx
> +
Maybe it should include an example call to Github API with `Octokit` + `Codegen` setup?

2022-08-01 09:53 UTC, charlypoly commented on pages/blog/slack-bot-with-cloudflare.mdx
> +
putting back @kamilkisiela's feedback:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1252066/182122975-18297b71-0d46-45f2-96e9-604df312586c.png">

2022-08-01 10:01 UTC, charlypoly requested changes
@TuvalSimha, nice article! 🤓 

I've left some suggestions for phrasing, mainly to avoid the use of too many combined superlatives (ex: "very super [...]").

2022-08-01 10:02 UTC, charlypoly commented
@TuvalSimha, I also fixed the Vercel build 🤓 

Let me know if you need some illustrations 👨🏼‍🎨

2022-10-11 13:03 UTC, charlypoly approved these changes
Let's publish tomorrow

2022-10-12 08:58 UTC, merged