Blog Post: GraphQL Armor Support for GraphQL Yoga
the-guild-org/the-guild-website pull request #804
Opened 2022-08-23 15:51 UTC by glimow

Adding the blog post to announce [GraphQL Armor](https://github.com/Escape-Technologies/graphql-armor)'s support for GraphQL Yoga 2

2022-08-23 17:23 UTC, Urigo requested changes

2022-08-24 08:36 UTC, notrab commented
@n1ru4l @Urigo we also have [this video](https://graphql.wtf/episodes/55-graphql-armor) showing Armor + Yoga if we want to embed it.

```md
<YouTube youTubeId="Rklux1aF5Tc" />
```

2022-08-24 08:36 UTC, notrab commented on pages/blog/announcing-graphql-armor-support-for-graphql-yoga-2.mdx
> +
```suggestion

<YouTube youTubeId="Rklux1aF5Tc" />
```

2022-08-24 08:36 UTC, iCarossio commented
Yes that’s definitely an excellent idea!

2022-08-24 08:59 UTC, charlypoly commented on pages/blog/announcing-graphql-armor-support-for-graphql-yoga-2.mdx
> +  title: 'Improved Security with GraphQL Armor support for Yoga Server 2',
@n1ru4l ping me when done so I update the newsletter link 😅

2022-08-24 09:09 UTC, glimow commented
@n1ru4l @Urigo updated article title and cover to add both our companies logo.

2022-08-24 09:14 UTC, n1ru4l commented on pages/blog/improved-security-with-graphql-armor-support-for-yoga-server-2.mdx
> +```javascript=
```suggestion
```ts
```

2022-08-24 09:14 UTC, n1ru4l commented on pages/blog/improved-security-with-graphql-armor-support-for-yoga-server-2.mdx
> +```javascript=
```suggestion
```ts
```

2022-08-24 11:22 UTC, merged